research_task:
  description: >
    Conduct thorough research on travel options for {location} starting {date} for {days} days. Focus on:
    1. Detailed itineraries for each day with time slots in 24-hour format.
    2. Travel attractions and landmarks.
    3. Restaurant recommendations featuring {preferred_food} cuisine.
    4. Accommodation options and local experiences.
    5. Overall travel plan keeping in mind a budget of {budget}.
  expected_output: >
    A comprehensive research document covering all travel aspects for {location}, including a day-by-day itinerary with exact times.
  agent: local_analyst

analysis_task_budget:
  description: >
    Create a budget-friendly travel plan for {location} that includes a detailed itinerary with daily schedules in 24-hour format,
    meal timings, and cost breakdowns for activities and restaurants.
  expected_output: >
    A comprehensive budget plan for {location}, including a day-by-day itinerary, restaurant recommendations, and timing details.
  agent: budget_planner
  context:
    - research_task
  output_file: output/budget_travel_plan.md

analysis_task_news:
  description: >
    Analyze the latest travel trends, safety information, local events, and restaurant reviews for {location}.
  expected_output: >
    A report summarizing key trends, safety info, local events, and dining recommendations for travelers.
  agent: news_analyst
  context:
    - research_task
  output_file: output/news_travel_report.md
